pimcore:
  objects:
    class_definitions:
      layout:
        map:
          dataQuality: BigJabber\DataQualityBundle\Model\DataObject\ClassDefinition\Layout\DataQuality

doctrine_migrations:
  migrations_paths:
    'BigJabber\DataQualityBundle\Migrations': '@DataQualityBundle/Migrations'
